import type { Metadata } from "next";
import "./globals.css";

// Theme provider importation
import ThemeProvider from "@/contexts/ThemeContext/ThemeProvider";

export const metadata: Metadata = {
  title: "Calculator project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
