import type { Metadata } from "next";
import "./globals.css";

// Theme provider importation
import ThemeContext from "@/contexts/ThemeContext";

export const metadata: Metadata = {
  title: "Calculator project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeContext>{children}</ThemeContext>
      </body>
    </html>
  );
}
